### ISSUE TITLE
npm install produce FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by androidotai** [PolymerElements/paper-button#188]
### Description
npm install taking longer time to execute and produce 
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### Expected outcome
The npm install execute successfully

### Actual outcome
The npm install execute unsuccessfully

### Steps to reproduce
npm install

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### Logs
.....
8944 verbose lifecycle @polymer/paper-button@3.0.1~prepare: CWD: D:\TUTORIALS\StencilsTuts_Codes\paper-button
8945 silly lifecycle @polymer/paper-button@3.0.1~prepare: Args: [ '/d /s /c', 'npm run generate-types' ]
8946 silly lifecycle @polymer/paper-button@3.0.1~prepare: Returned: code: 134  signal: null
8947 info lifecycle @polymer/paper-button@3.0.1~prepare: Failed to exec prepare script
8948 verbose stack Error: @polymer/paper-button@3.0.1 prepare: `npm run generate-types`
8948 verbose stack Exit status 134
8948 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v10.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
8948 verbose stack     at EventEmitter.emit (events.js:182:13)
8948 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v10.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
8948 verbose stack     at ChildProcess.emit (events.js:182:13)
8948 verbose stack     at maybeClose (internal/child_process.js:957:16)
8948 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
8949 verbose pkgid @polymer/paper-button@3.0.1
8950 verbose cwd D:\TUTORIALS\StencilsTuts_Codes\paper-button
8951 verbose Windows_NT 10.0.17763
8952 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
8953 verbose node v10.1.0
8954 verbose npm  v6.9.1-next.0
8955 error code ELIFECYCLE
8956 error errno 134
8957 error @polymer/paper-button@3.0.1 prepare: `npm run generate-types`
8957 error Exit status 134
8958 error Failed at the @polymer/paper-button@3.0.1 prepare script.
8958 error This is probably not a problem with npm. There is likely additional logging output above.
8959 verbose exit [ 134, true ]

**Comment by keanulee** [comment]
Wasn't able to reproduce on macOS 10.14.4 with Node v10.14.2 and NPM 6.4.1. More details?

**Comment by androidotai** [comment]
> Wasn't able to reproduce on macOS 10.14.4 with Node v10.14.2 and NPM 6.4.1. More details?

Windows 10, node v10.1.0 and NPM 6.9.1-next.0.

**Comment by DrNiels** [comment]
I'm having the same issue. I use Windows 10 as well, with node v9.11.1 and npm 5.6.0.
